import { firebaseConfig, SCRUTINY_ADMIN_EMAILS } from "./firebase-config.js";
import { entitledCourses } from "./course-catalog.js?v=2";
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, getIdTokenResult, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const SOURCES = [
  {id:"mathematics",name:"Mathematics",icon:"📐",color:"#1769aa",file:"data/class10/textbooks/mathematics/catalog.json"},
  {id:"physics",name:"Physical Science",icon:"⚛️",color:"#7356c8",file:"data/class10/textbooks/physics/catalog.json"},
  {id:"biology",name:"Biological Science",icon:"🧬",color:"#16815b",file:"data/class10/textbooks/biology/catalog.json"},
  {id:"social-science",name:"Social Studies",icon:"🌏",color:"#d06b2d",file:"data/class10/textbooks/social-science/catalog.json"},
];
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const dayKey = (date=new Date()) => date.toISOString().slice(0,10);
const STORE = "scrutiny_class10_board_v1";
let library = {}, activeSubject = SOURCES[0].id, activeChapter = null, activeMode = "learn", flashIndex = 0, flashRevealed = false, quiz = null;
let state = {lastVisit:"",streak:1,activities:0,lastChapter:"",chapters:{},mistakes:[],reviews:{},mission:{date:"",done:[]},examDate:"",testHistory:[]};

function loadState(){try{state={...state,...JSON.parse(localStorage.getItem(STORE)||"{}")};}catch{}const today=dayKey();if(state.lastVisit!==today){const d=new Date();d.setDate(d.getDate()-1);state.streak=state.lastVisit===dayKey(d)?(state.streak||0)+1:1;state.lastVisit=today;}if(state.mission?.date!==today)state.mission={date:today,done:[]};save(false);}
function save(render=true){localStorage.setItem(STORE,JSON.stringify(state));if(render){renderMission();renderReadiness();renderMistakes();renderStats();}}
function chapterProgress(id){state.chapters[id]||={learn:0,remember:0,practice:0,write:0,test:0,revision:0};return state.chapters[id];}
function mastery(id){const p=chapterProgress(id);return Math.round(p.learn*.17+p.remember*.15+p.practice*.2+p.write*.2+p.test*.2+p.revision*.08);}
function complete(skill,value=100){if(!activeChapter)return;const p=chapterProgress(activeChapter.id);p[skill]=Math.max(p[skill]||0,value);state.activities+=1;state.lastChapter=activeChapter.id;const mi={learn:0,remember:1,practice:2,write:3,test:3,revision:4}[skill];if(mi!==undefined&&!state.mission.done.includes(mi))state.mission.done.push(mi);save();toast(`${skill[0].toUpperCase()+skill.slice(1)} progress saved ✓`);}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove("show"),2500);}
function subjectMeta(id){return SOURCES.find(s=>s.id===id)||SOURCES[0];}
function findChapter(id){for(const [subject,data] of Object.entries(library)){const chapter=data.chapters.find(c=>c.id===id);if(chapter)return{subject,chapter};}return null;}
function allChapters(){return Object.entries(library).flatMap(([subject,data])=>data.chapters.map(chapter=>({subject,chapter})));}
function answerText(question){if(Array.isArray(question.options))return `${question.options[question.answer]}. ${question.explanation||""}`.trim();return question.answer||question.explanation||"";}
function flashcards(chapter){return [...(chapter.vsaq||[]),...(chapter.saq||[]),...(chapter.laq||[]),...(chapter.mcqs||[])].map(q=>({id:q.id,q:q.question,a:answerText(q)}));}
function keywords(text){const stop=new Set("this that with from into where which their there about have has been were will would should could what when then than because through also and the are for not but its they them your you can".split(" "));return [...new Set(String(text).replace(/[^A-Za-z0-9 ]/g," ").split(/\s+/).filter(w=>w.length>5&&!stop.has(w.toLowerCase())).map(w=>w.replace(/^./,c=>c.toUpperCase())))].slice(0,10);}
function markPoints(text,marks){const raw=String(text).split(/(?=\d+\)|\d+\.|;)|(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);return raw.slice(0,Math.max(2,Math.min(Number(marks)||4,6)));
}

async function loadLibrary(){const rows=await Promise.all(SOURCES.map(async source=>{const catalog=await fetch(source.file,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(source.file);return r.json();});const chapters=await Promise.all(catalog.chapters.map(chapter=>chapter.file?fetch(chapter.file,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(chapter.file);return r.json();}):chapter));return[source.id,{...catalog,chapters}];}));library=Object.fromEntries(rows);}
function renderStats(){$("streak").textContent=state.streak||1;$("activities").textContent=state.activities||0;$("dueCount").textContent=state.mistakes.length+Object.values(state.reviews||{}).filter(r=>new Date(r.due)<=new Date()).length;}
function renderMission(){const items=[["📖","Learn","One high-yield concept set","15 min"],["🧠","Remember","Flashcard active recall","10 min"],["🎯","Practise","Mark-wise board questions","20 min"],["✍️","Write","One model board answer","10 min"],["↻","Improve","Review today’s errors","5 min"]];$("missionList").innerHTML=items.map((x,i)=>`<div class="mission-item ${state.mission.done.includes(i)?"done":""}"><i>${x[0]}</i><span><b>${x[1]}</b><small>${x[2]}</small></span><time>${x[3]}</time></div>`).join("");$("missionCount").textContent=`${state.mission.done.length}/5`;$("missionBar").style.width=`${state.mission.done.length*20}%`;const next=["learn","remember","practice","write","improve"].find((_,i)=>!state.mission.done.includes(i))||"improve";$("missionAction").textContent=state.mission.done.length===5?"MISSION COMPLETE ✓":`CONTINUE WITH ${next.toUpperCase()} →`;$("missionAction").dataset.mode=next;}
function renderSubjects(){$("subjectTabs").innerHTML=SOURCES.map(s=>`<button style="--subject-color:${s.color}" class="${s.id===activeSubject?"active":""}" data-subject="${s.id}">${s.icon} ${s.name}</button>`).join("");document.querySelectorAll("[data-subject]").forEach(b=>b.onclick=()=>{activeSubject=b.dataset.subject;renderSubjects();renderChapters();});}
function renderChapters(){const meta=subjectMeta(activeSubject),chapters=library[activeSubject]?.chapters||[];$("chapterGrid").innerHTML=chapters.map((ch,i)=>{const cards=flashcards(ch).length,written=(ch.vsaq?.length||0)+(ch.saq?.length||0)+(ch.laq?.length||0);return `<article class="chapter-card" style="--subject-color:${meta.color}"><span class="chapter-number">${String(i+1).padStart(2,"0")}</span><h3>${esc(ch.name)}</h3><p>${esc(ch.overview)}</p><div class="bank-counts"><span>${cards} recall cards</span><span>${ch.mcqs?.length||0} MCQs</span><span>${written} written</span></div><button data-open="${esc(ch.id)}">${state.lastChapter===ch.id?"CONTINUE":"START"} • ${mastery(ch.id)}% READY</button></article>`;}).join("")||'<div class="empty">This subject bank is being prepared.</div>';document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openChapter(b.dataset.open));}
function openChapter(id,mode="learn"){const found=findChapter(id);if(!found)return;activeSubject=found.subject;activeChapter=found.chapter;activeMode=mode;state.lastChapter=id;save(false);const meta=subjectMeta(activeSubject);$("chapterSubject").textContent=`${meta.icon} ${meta.name}`;$("chapterTitle").textContent=activeChapter.name;$("chapterOverview").textContent=activeChapter.overview;const written=(activeChapter.vsaq?.length||0)+(activeChapter.saq?.length||0)+(activeChapter.laq?.length||0);$("chapterCounts").innerHTML=`<span>${flashcards(activeChapter).length} recall prompts</span><span>${activeChapter.mcqs?.length||0} MCQs</span><span>${written} written questions</span><span>${mastery(id)}% chapter readiness</span>`;$("workspace").hidden=false;setMode(mode);$("workspace").scrollIntoView({behavior:"smooth",block:"start"});}
function setMode(mode){activeMode=mode;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));({learn:renderLearn,remember:renderRemember,practice:renderPractice,write:renderWrite,test:renderTestHub,improve:renderImprove}[mode]||renderLearn)();}
function intro(title,copy,action=""){return `<div class="learning-intro"><div><span class="eyebrow">${activeMode.toUpperCase()} • BOARD MASTERY</span><h3>${title}</h3><p>${copy}</p></div>${action}</div>`;}
function renderLearn(){const qs=[...(activeChapter.vsaq||[]),...(activeChapter.saq||[]),...(activeChapter.laq||[])];const cards=qs.slice(0,10).map((q,i)=>`<article class="concept-card"><span>HIGH-YIELD ${String(i+1).padStart(2,"0")}</span><h4>${esc(q.question)}</h4><p>${esc(q.answer)}</p></article>`).join("");$("learningPanel").innerHTML=intro("What you must know for Boards","Read for understanding, then use the checklist to confirm that you can explain each point without looking.",'<button class="complete-action" id="completeLearn">MARK LEARN COMPLETE</button>')+`<div class="concept-grid">${cards}</div><div class="board-check"><h4>✓ Board checklist</h4>${qs.slice(0,6).map((q,i)=>`<label><input type="checkbox"> <span>I can answer: ${esc(q.question)}</span></label>`).join("")}</div>`;$("completeLearn").onclick=()=>complete("learn");}
function reviewDue(card){const row=state.reviews?.[card.id];return !row||new Date(row.due)<=new Date();}
function scheduleCard(card,days){state.reviews[card.id]={due:new Date(Date.now()+days*86400000).toISOString(),interval:days,chapterId:activeChapter.id};save();toast(days===0?"Card stays in Today":"Next review scheduled ✓");}
function renderRemember(view="flashcards"){const cards=flashcards(activeChapter);if(view==="quick"){const defs=(activeChapter.vsaq||[]).slice(0,6),long=[...(activeChapter.saq||[]),...(activeChapter.laq||[])].slice(0,4);$("learningPanel").innerHTML=intro("Revise in 5 minutes","A compact chapter sheet for rapid recall before practice.")+`<div class="revision-switch"><button data-revision="flashcards">Flashcards</button><button class="active" data-revision="quick">5-minute sheet</button><button data-revision="night">Night before</button></div><div class="quick-sheet"><article><h4>Definitions & one-mark facts</h4>${defs.map(q=>`<p><b>${esc(q.question)}</b><br>${esc(q.answer)}</p>`).join("")}</article><article><h4>Processes & long answers</h4>${long.map(q=>`<p><b>${esc(q.question)}</b><br>${esc(q.answer)}</p>`).join("")}</article></div>`;bindRevision();return;}if(view==="night"){renderNightBefore(false);return;}flashIndex=Math.min(flashIndex,cards.length-1);const card=cards[flashIndex];$("learningPanel").innerHTML=intro("Spaced-revision flashcards",`${cards.filter(reviewDue).length} cards are due. Choose Today, 3, 7 or 21 days after recalling each answer.`)+`<div class="revision-switch"><button class="active" data-revision="flashcards">Flashcards</button><button data-revision="quick">5-minute sheet</button><button data-revision="night">Night before</button></div><div class="flashcard-stage"><div class="flashcard" id="flashcard"><div><span>${flashRevealed?"BOARD ANSWER":"ACTIVE RECALL • TAP TO REVEAL"}</span>${flashRevealed?`<p>${esc(card.a)}</p>`:`<h3>${esc(card.q)}</h3>`}</div></div><div class="flash-controls"><button id="prevFlash" ${flashIndex===0?"disabled":""}>←</button><strong>${flashIndex+1} / ${cards.length}</strong><button id="nextFlash">→</button></div>${flashRevealed?'<div class="question-actions"><button data-gap="0">Again today</button><button data-gap="3">3 days</button><button data-gap="7">7 days</button><button data-gap="21">21 days</button></div>':""}</div>`;$("flashcard").onclick=()=>{flashRevealed=!flashRevealed;renderRemember();};$("prevFlash").onclick=()=>{flashIndex--;flashRevealed=false;renderRemember();};$("nextFlash").onclick=()=>{if(flashIndex<cards.length-1){flashIndex++;flashRevealed=false;renderRemember();}else complete("remember");};document.querySelectorAll("[data-gap]").forEach(b=>b.onclick=()=>{scheduleCard(card,Number(b.dataset.gap));if(flashIndex<cards.length-1){flashIndex++;flashRevealed=false;renderRemember();}else complete("remember");});bindRevision();}
function bindRevision(){document.querySelectorAll("[data-revision]").forEach(b=>b.onclick=()=>renderRemember(b.dataset.revision));}
function practiceItems(type){if(type==="mcqs")return activeChapter.mcqs||[];if(type==="pyq")return [...(activeChapter.vsaq||[]),...(activeChapter.saq||[]),...(activeChapter.laq||[]),...(activeChapter.mcqs||[])].filter(q=>q.year||q.pyqYear);return activeChapter[type]||[];}
function renderPractice(type="vsaq"){const labels={vsaq:"1–2 mark",saq:"4 mark",laq:"Long answer",mcqs:"MCQs",pyq:"Verified PYQs"},items=practiceItems(type),visibleItems=type==="mcqs"?items:items.slice(0,20),empty=type==="pyq"?'<div class="empty"><b>No year-verified PYQs are tagged in this chapter yet.</b><p>Year and frequency appear only after source verification. Board-style questions remain available in the other tabs.</p></div>':'<div class="empty">No questions are published in this format yet.</div>';$("learningPanel").innerHTML=intro("Practice arranged like the board paper","Move from short recall to structured long answers. Every answer shows the points that earn marks; PYQ years are never invented.")+`<div class="practice-switch">${Object.entries(labels).map(([id,label])=>`<button class="${id===type?"active":""}" data-practice="${id}">${label} (${practiceItems(id).length})</button>`).join("")}</div><div class="question-list">${items.length?visibleItems.map((q,i)=>`<article class="practice-card"><span class="marks-badge">${q.year||q.pyqYear?`PYQ ${q.year||q.pyqYear}`:`${q.marks||1} MARK${Number(q.marks||1)>1?"S":""}`}</span><div><h4>${i+1}. ${esc(q.question)}</h4><p>${esc(q.difficulty||"Board practice")}${q.sourcePage?` • Textbook p. ${q.sourcePage}`:""}</p>${Array.isArray(q.options)?`<ol class="mcq-preview" type="A">${q.options.map(option=>`<li>${esc(option)}</li>`).join("")}</ol>`:""}</div><button class="outline" data-mastered="${esc(q.id)}">I can answer</button><details><summary>Show answer + marking points</summary><div class="marking-points"><p>${esc(answerText(q))}</p><ol>${markPoints(answerText(q),q.marks).map(p=>`<li>${esc(p)}</li>`).join("")}</ol></div></details></article>`).join(""):empty}</div>`;document.querySelectorAll("[data-practice]").forEach(b=>b.onclick=()=>renderPractice(b.dataset.practice));document.querySelectorAll("[data-mastered]").forEach(b=>b.onclick=()=>{complete("practice",Math.min(100,(chapterProgress(activeChapter.id).practice||0)+10));b.textContent="Mastered ✓";b.disabled=true;});}
function writingQuestions(){return [...(activeChapter.saq||[]),...(activeChapter.laq||[]),...(activeChapter.vsaq||[])];}
function renderWrite(index=0){const items=writingQuestions(),q=items[index]||items[0],points=markPoints(q.answer,q.marks),keys=keywords(q.answer);$("learningPanel").innerHTML=intro("Answer Writing Lab","Knowledge earns marks only when the examiner can see the right structure, keywords and steps.")+`<div class="answer-lab"><div class="answer-prompt"><span class="eyebrow">QUESTION • ${q.marks||1} MARKS • ${Math.max(2,(q.marks||1)*2)} MIN</span><select id="writingSelect">${items.map((x,i)=>`<option value="${i}" ${i===index?"selected":""}>${i+1}. ${esc(x.question)}</option>`).join("")}</select><h3>${esc(q.question)}</h3><textarea id="studentAnswer" placeholder="Write your board answer here using points, keywords and a labelled diagram where needed..."></textarea><button class="primary small" id="assessAnswer">SELF-CHECK MY ANSWER</button><p id="writingFeedback"></p></div><div class="answer-model"><h4>How marks are earned</h4>${points.map((p,i)=>`<div class="structure-row"><b>Point ${i+1}</b><span>${esc(p)}</span></div>`).join("")}<h4>Keywords the examiner should see</h4><div class="keywords">${keys.map(k=>`<span>${esc(k)}</span>`).join("")}</div><div class="comparison"><div class="average"><b>Average answer</b><p>A single paragraph with the main idea, but few visible keywords or steps.</p></div><div class="topper"><b>Board-topper answer</b><p>Direct opening, numbered points, underlined keywords, complete steps and a labelled diagram/unit wherever required.</p></div></div></div></div>`;$("writingSelect").onchange=e=>renderWrite(Number(e.target.value));$("assessAnswer").onclick=()=>{const text=$("studentAnswer").value.trim();if(text.length<25){$("writingFeedback").textContent="Write a complete attempt first.";return;}const hits=keys.filter(k=>text.toLowerCase().includes(k.toLowerCase())).length,score=Math.max(35,Math.round(hits/Math.max(keys.length,1)*100));complete("write",score);$("writingFeedback").innerHTML=`Estimated structure score: <b>${score}%</b> • ${hits}/${keys.length} key terms found. Compare with the model and rewrite once.`;};}
function renderTestHub(){const subjectPool=(library[activeSubject]?.chapters||[]).flatMap(ch=>ch.mcqs||[]);$("learningPanel").innerHTML=intro("Tests that grow with your preparation","Begin with a quick check, then progress to chapter, subject and three-hour written-paper practice.")+`<div class="improve-grid"><article class="improve-card"><span class="eyebrow">10 QUESTIONS</span><h4>Quick Concept Check</h4><p>Fast recall and application with instant error capture.</p><button data-test-size="10" data-test-label="Quick Concept Check">Start quick check</button></article><article class="improve-card"><span class="eyebrow">25 QUESTIONS</span><h4>Chapter Test</h4><p>A broader check from this chapter’s published bank.</p><button data-test-size="25" data-test-label="Chapter Test">Start chapter test</button></article><article class="improve-card"><span class="eyebrow">30 QUESTIONS</span><h4>Subject Test</h4><p>Questions sampled across all published ${esc(subjectMeta(activeSubject).name)} chapters.</p><button id="subjectTest">Start subject test</button></article><article class="improve-card"><span class="eyebrow">3 HOURS • WRITTEN</span><h4>Board Simulation</h4><p>A mark-wise paper with model-answer self-checking.</p><button id="boardSimulation">Open simulation</button></article></div>`;document.querySelectorAll("[data-test-size]").forEach(b=>b.onclick=()=>startTest(null,Number(b.dataset.testSize),b.dataset.testLabel));$("subjectTest").onclick=()=>startTest(subjectPool,30,"Subject Test");$("boardSimulation").onclick=renderBoardSimulation;}
function startTest(customQuestions=null,size=10,label="Chapter Test"){const pool=customQuestions||[...(activeChapter?.mcqs||[])];if(!pool.length){$("learningPanel").innerHTML='<div class="empty">No MCQs are published for this selection yet.</div>';return;}quiz={questions:[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(size,pool.length)),index:0,score:0,wrong:[],started:Date.now(),label};renderTestQuestion();}
function renderBoardSimulation(){const questions=[...(activeChapter.vsaq||[]).slice(0,5),...(activeChapter.saq||[]).slice(0,4),...(activeChapter.laq||[]).slice(0,2)],marks=questions.reduce((n,q)=>n+Number(q.marks||1),0);$("learningPanel").innerHTML=intro("3-hour Board Simulation","Write on paper in exam conditions. Reveal marking points only after completing the attempt.")+`<div class="test-card"><p class="eyebrow">TIME: 3 HOURS • PRACTICE PAPER • ${marks} MARKS</p><h3>${esc(subjectMeta(activeSubject).name)} — ${esc(activeChapter.name)}</h3><ol>${questions.map(q=>`<li><p><b>[${q.marks||1} marks]</b> ${esc(q.question)}</p><details><summary>Self-check after the attempt</summary><div class="marking-points">${markPoints(q.answer,q.marks).map(p=>`<p>✓ ${esc(p)}</p>`).join("")}</div></details></li>`).join("")}</ol><button class="primary small" id="simulationComplete">I completed the paper</button></div>`;$("simulationComplete").onclick=()=>complete("test",100);}
function renderTestQuestion(){const q=quiz.questions[quiz.index];if(!q){finishTest();return;}$("learningPanel").innerHTML=`<div class="quiz-shell">${intro(quiz.label,"A timed concept check. Incorrect answers enter My Mistakes automatically.")}<div class="quiz-progress"><span style="width:${quiz.index/quiz.questions.length*100}%"></span></div><p class="eyebrow">QUESTION ${quiz.index+1} OF ${quiz.questions.length}</p><h3>${esc(q.question)}</h3><div class="quiz-options">${q.options.map((o,i)=>`<button data-option="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join("")}</div><div id="quizFeedback"></div></div>`;document.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>answerTest(b,Number(b.dataset.option),q));}
function answerTest(button,chosen,q){document.querySelectorAll("[data-option]").forEach(b=>{b.disabled=true;if(Number(b.dataset.option)===q.answer)b.classList.add("correct");});const correct=chosen===q.answer;button.classList.add(correct?"correct":"wrong");if(correct){quiz.score++;state.mistakes=state.mistakes.filter(m=>m.id!==q.id);}else{quiz.wrong.push(q);if(!state.mistakes.some(m=>m.id===q.id))state.mistakes.push({id:q.id,question:q.question,answer:answerText(q),chapterId:activeChapter?.id||q.__chapterId,subject:activeSubject,category:"Concept",date:dayKey()});}save(false);$("quizFeedback").innerHTML=`<div class="feedback"><b>${correct?"Correct":"Not correct"}.</b> ${esc(q.explanation||`Answer: ${q.options[q.answer]}`)}</div><div class="question-actions"><button id="nextTest">${quiz.index===quiz.questions.length-1?"See diagnostic":"Next question"}</button></div>`;$("nextTest").onclick=()=>{quiz.index++;renderTestQuestion();};}
function finishTest(){const pct=Math.round(quiz.score/quiz.questions.length*100),seconds=Math.round((Date.now()-quiz.started)/1000);state.testHistory.push({date:dayKey(),score:pct,chapterId:activeChapter?.id||"weak",seconds});if(activeChapter)complete("test",pct);else save();$("learningPanel").innerHTML=`<div class="test-card"><span class="eyebrow">DIAGNOSTIC COMPLETE</span><h2>${quiz.score}/${quiz.questions.length} • ${pct}%</h2><p>${pct>=80?"Strong result. Move to written answers and a full chapter test.":"Review the saved mistakes, then retry the weak concepts."}</p><div class="diagnostic-result"><span><b>${pct}%</b>Concept</span><span><b>${Math.max(0,pct-8)}%</b>Recall</span><span><b>${activeSubject==="mathematics"||activeSubject==="physics"?pct:"—"}</b>Numericals</span><span><b>${chapterProgress(activeChapter?.id||"").write||0}%</b>Writing</span><span><b>${seconds}s</b>Time</span></div><div class="question-actions"><button id="retryTest">Retry test</button><button id="reviewErrors">Review mistakes</button></div></div>`;$("retryTest").onclick=()=>startTest();$("reviewErrors").onclick=()=>document.querySelector("#mistakes").scrollIntoView({behavior:"smooth"});}
function renderImprove(){const p=chapterProgress(activeChapter.id),due=state.mistakes.filter(m=>m.chapterId===activeChapter.id).length,weak=Object.entries(p).sort((a,b)=>a[1]-b[1])[0];$("learningPanel").innerHTML=intro("Your improvement plan","The platform converts activity data into one clear next step.")+`<div class="improve-grid"><article class="improve-card"><span class="eyebrow">WEAKEST SKILL</span><h4>${esc(weak[0])} • ${weak[1]}%</h4><p>Complete one focused ${esc(weak[0])} activity now.</p><button data-improve="${weak[0]}">Improve skill</button></article><article class="improve-card"><span class="eyebrow">ERROR NOTEBOOK</span><h4>${due} chapter mistakes</h4><p>Correct them before they repeat in the board paper.</p><button data-scroll-mistakes>Open mistakes</button></article><article class="improve-card"><span class="eyebrow">CHAPTER MASTERY</span><h4>${mastery(activeChapter.id)}% ready</h4><p>Readiness combines concepts, recall, practice, writing, tests and revision.</p><button data-improve="test">Run a test</button></article></div>`;document.querySelectorAll("[data-improve]").forEach(b=>b.onclick=()=>setMode(b.dataset.improve==="revision"?"remember":b.dataset.improve));document.querySelector("[data-scroll-mistakes]").onclick=()=>$("mistakes").scrollIntoView({behavior:"smooth"});}
function skillAverages(){const chapters=allChapters();const skills=["learn","remember","practice","write","test","revision"];return Object.fromEntries(skills.map(k=>[k,chapters.length?Math.round(chapters.reduce((n,x)=>n+(chapterProgress(x.chapter.id)[k]||0),0)/chapters.length):0]));}
function renderReadiness(){const skills=skillAverages(),score=Math.round(skills.learn*.16+skills.remember*.14+skills.practice*.2+skills.write*.22+skills.test*.2+skills.revision*.08);$("readinessScore").textContent=`${score}%`;$("readinessRing").style.setProperty("--score",score);const labels={learn:"Concept knowledge",remember:"Recall",practice:"Board practice",write:"Answer writing",test:"Tests",revision:"Error revision"};$("diagnostics").innerHTML=Object.entries(labels).map(([k,label])=>`<div class="diagnostic-row"><span>${label}</span><div class="track"><i style="width:${skills[k]}%"></i></div><b>${skills[k]}%</b></div>`).join("");const ranked=Object.entries(skills).sort((a,b)=>a[1]-b[1]),weak=ranked[0];$("coachTitle").textContent=state.activities?`Improve ${labels[weak[0]].toLowerCase()} next`:"Begin your first chapter";$("coachText").textContent=state.activities?`${labels[weak[0]]} is currently your lowest skill at ${weak[1]}%. One focused activity will improve your readiness more than random practice.`:"Start with the Learn section of your first chapter. Your plan will adapt after every activity.";$("coachAction").dataset.skill=weak[0];$("subjectReadiness").innerHTML=SOURCES.map(s=>{const chapters=library[s.id]?.chapters||[],value=chapters.length?Math.round(chapters.reduce((n,c)=>n+mastery(c.id),0)/chapters.length):0,status=value>=75?"Strong":value>=40?"Improving":"Needs focus",color=value>=75?"#16815b":value>=40?"#d98b16":"#cf4a4a";return `<article class="subject-status" style="--status:${color}"><header><b>${s.icon} ${s.name}</b><strong>${value}%</strong></header><small>${status}</small></article>`;}).join("");}
function renderMistakes(filter="All"){const cats=["All","Concept","Memory","Calculation","Careless","Answer-writing"];$("mistakeFilters").innerHTML=cats.map(c=>`<button data-filter="${c}" class="${c===filter?"active":""}">${c} ${c==="All"?state.mistakes.length:state.mistakes.filter(m=>m.category===c).length}</button>`).join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>renderMistakes(b.dataset.filter));const rows=filter==="All"?state.mistakes:state.mistakes.filter(m=>m.category===filter);$("mistakeList").innerHTML=rows.length?rows.map(m=>`<article class="mistake-card"><div><small>${esc(findChapter(m.chapterId)?.chapter.name||"Board revision")} • ${esc(m.date)}</small><h3>${esc(m.question)}</h3><p><b>Correct answer:</b> ${esc(m.answer)}</p></div><div><select data-category="${esc(m.id)}">${cats.slice(1).map(c=>`<option ${c===m.category?"selected":""}>${c}</option>`).join("")}</select><button data-revised="${esc(m.id)}">Revised ✓</button></div></article>`).join(""):'<div class="empty"><b>No mistakes waiting 🎉</b><p>Incorrect test answers will be saved here automatically.</p></div>';document.querySelectorAll("[data-category]").forEach(s=>s.onchange=()=>{const item=state.mistakes.find(m=>m.id===s.dataset.category);if(item)item.category=s.value;save();});document.querySelectorAll("[data-revised]").forEach(b=>b.onclick=()=>{state.mistakes=state.mistakes.filter(m=>m.id!==b.dataset.revised);if(activeChapter)complete("revision");else save();});}
function weakQuestions(){return state.mistakes.map(m=>{const found=findChapter(m.chapterId),q=found?.chapter.mcqs?.find(x=>x.id===m.id);return q?{...q,__chapterId:m.chapterId}:null;}).filter(Boolean);}
function renderBoardMode(){const phases=[[90,"Complete concepts"],[60,"Heavy practice"],[30,"PYQs + revision"],[15,"Sample papers"],[7,"High-yield revision"],[1,"Exam Rescue"]];let days=null;if(state.examDate){days=Math.ceil((new Date(state.examDate+"T00:00:00")-new Date(new Date().toDateString()))/86400000);$("examDate").value=state.examDate;}const active=days===null?-1:phases.findIndex((p,i)=>days<=p[0]&&(i===phases.length-1||days>phases[i+1][0]));$("countdownTitle").textContent=days===null?"Set your exam date and activate the countdown.":days<0?"Board exam date has passed.":`${days} days to your first board exam.`;$("countdownCopy").textContent=days===null?"Your recommended phase changes automatically from concept completion to practice, verified PYQs, sample papers and exam rescue.":days>90?"Build a steady foundation now. The focused 90-day cycle will activate automatically.":`Current focus: ${phases[Math.max(0,active)]?.[1]||"Exam preparation"}. Your daily mission should prioritise this phase.`;$("timeline").innerHTML=phases.map((p,i)=>`<div class="phase ${i===active?"active":""}"><b>${p[0]} days</b><small>${p[1]}</small></div>`).join("");}
function renderNightBefore(dialog=true){const chapters=activeChapter?[activeChapter]:allChapters().map(x=>x.chapter),items=chapters.slice(0,6).map(ch=>`<article><span class="eyebrow">${esc(ch.name)}</span>${(ch.vsaq||[]).slice(0,4).map(q=>`<p><b>${esc(q.question)}</b><br>${esc(q.answer)}</p>`).join("")}</article>`).join("");const content=`<span class="eyebrow">EXAM RESCUE • NIGHT BEFORE</span><h2>Only the essentials. No new learning.</h2><p>Review definitions, formulae, diagrams/steps and your own errors. Stop heavy study in time to sleep.</p><div class="night-grid">${items}</div>`;if(dialog){$("dialogContent").innerHTML=content;$("activityDialog").showModal();}else{$("learningPanel").innerHTML=intro("Night Before Exam","Only essential definitions, steps and high-yield recall from this chapter.")+`<div class="revision-switch"><button data-revision="flashcards">Flashcards</button><button data-revision="quick">5-minute sheet</button><button class="active" data-revision="night">Night before</button></div><div class="night-grid">${items}</div>`;bindRevision();}}
function parentReport(){const score=$("readinessScore").textContent,weak=Object.entries(skillAverages()).sort((a,b)=>a[1]-b[1])[0],text=`Scrutiny Academy – Class 10 Telangana SSC Progress\nBoard Readiness: ${score}\nActivities completed: ${state.activities}\nCurrent streak: ${state.streak} day(s)\nMistakes awaiting revision: ${state.mistakes.length}\nPriority area: ${weak[0]} (${weak[1]}%)\nRecommended next step: complete today's guided 60-minute mission.`;navigator.clipboard?.writeText(text).then(()=>toast("Parent progress report copied ✓")).catch(()=>prompt("Copy this report",text));}
function bind(){document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$("allChapters").onclick=()=>$("subjects").scrollIntoView({behavior:"smooth"});$("startMission").onclick=()=>{const found=findChapter(state.lastChapter)||allChapters()[0];if(found)openChapter(found.chapter.id,"learn");};$("missionAction").onclick=()=>{const found=findChapter(state.lastChapter)||allChapters()[0];if(found)openChapter(found.chapter.id,$("missionAction").dataset.mode);};$("coachAction").onclick=()=>{const found=findChapter(state.lastChapter)||allChapters()[0];let skill=$("coachAction").dataset.skill||"learn";if(skill==="revision")skill="remember";if(found)openChapter(found.chapter.id,skill);};$("weakAreaTest").onclick=()=>{const qs=weakQuestions();if(!qs.length){toast("Complete a test first—wrong answers will build this practice set.");return;}const found=findChapter(qs[0].__chapterId);if(found){activeChapter=found.chapter;activeSubject=found.subject;$("workspace").hidden=false;quiz=null;startTest(qs,Math.min(10,qs.length),"Weak Area Test");$("workspace").scrollIntoView({behavior:"smooth"});}};$("examDateForm").onsubmit=e=>{e.preventDefault();state.examDate=$("examDate").value;save(false);renderBoardMode();toast("90-Day Board Mode activated ✓");};$("nightBefore").onclick=()=>renderNightBefore(true);$("parentReport").onclick=parentReport;$("closeDialog").onclick=()=>$("activityDialog").close();$("menuBtn").onclick=()=>{const open=$("mainNav").classList.toggle("open");$("menuBtn").setAttribute("aria-expanded",open);};$("mainNav").onclick=e=>{if(e.target.closest("a"))$("mainNav").classList.remove("open");};}
function friendlyName(profile,user){let value=String(profile.preferredName||profile.fullName||profile.name||user.displayName||(user.email||"").split("@")[0]||"Student");value=value.replace(/^(i[._-]?am|its|official)[._-]?/i,"").replace(/[._-]+/g," ").replace(/\d+/g," ").trim();return value?value.split(" ").slice(0,2).map(x=>x.charAt(0).toUpperCase()+x.slice(1).toLowerCase()).join(" "):"Student";}
async function openPortal(auth,user,profile){if(!entitledCourses(profile).includes("class10")&&profile.founderAccess!==true){location.replace("payment.html?course=class10");return;}$("welcome").textContent=`${friendlyName(profile,user)}, know what to study. Practise it. Write it like a topper.`;$("logoutBtn").onclick=async()=>{await signOut(auth);location.replace("login.html");};document.documentElement.classList.remove("auth-check");}
async function initAuth(){const configured=firebaseConfig.apiKey&&firebaseConfig.apiKey!=="REPLACE_ME";if(!configured){location.replace("login.html?error=config");return;}const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);onAuthStateChanged(auth,async user=>{if(!user){location.replace("login.html");return;}const admin=SCRUTINY_ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((user.email||"").toLowerCase());let founder=admin;if(!founder){try{founder=(await getIdTokenResult(user,true)).claims.founder===true;}catch{}}let profile={};try{const snap=await getDoc(doc(db,"students",user.uid));if(snap.exists())profile=snap.data();}catch(error){console.warn("Profile unavailable",error);}if(founder)profile={...profile,accessStatus:"active",founderAccess:true};if(profile.accessStatus!=="active"&&!founder){location.replace("payment.html?course=class10");return;}await openPortal(auth,user,profile);});}

loadState();
try{await loadLibrary();renderStats();renderMission();renderSubjects();renderChapters();renderReadiness();renderMistakes();renderBoardMode();bind();await initAuth();}catch(error){console.error(error);document.documentElement.classList.remove("auth-check");document.body.innerHTML='<main><div class="empty"><h2>Class 10 portal could not load.</h2><p>Please refresh or contact Scrutiny Academy support.</p></div></main>';}
