/* 2025-26 Telangana Class 8 English-medium textbook structure.
   Practice material is original and generated from curated chapter topic maps. */
(function(){
const curriculum={
"Mathematics":{icon:"➗",color:"#6d28d9",chapters:[
["math-01","Rational Numbers","standard form|equivalent rational numbers|number line|comparison|addition|subtraction|multiplication|division|properties|identity and inverse"],
["math-02","Linear Equations in One Variable","equation and expression|balance principle|one-step equations|variables on both sides|brackets|fractional coefficients|word statements|consecutive numbers|age and quantity problems|verification"],
["math-03","Construction of Quadrilaterals","sufficient measurements|four sides and a diagonal|three sides and two angles|two sides and three angles|diagonal method|parallelogram construction|rectangle construction|rhombus construction|compass arcs|verification by measurement"],
["math-04","Exponents and Powers","base and exponent|product law|quotient law|power of a power|power of a product|zero exponent|negative exponent|standard form|comparing powers|powers of ten"],
["math-05","Comparing Quantities using Proportion","ratio and proportion|percentage|percentage change|profit and loss|discount|simple interest|repeated percentage change|tax and charges|unitary method|comparing offers"],
["math-06","Square Roots and Cube Roots","perfect squares|square roots|prime factor method|long division method|estimating roots|Pythagorean triples|perfect cubes|cube roots|smallest multiplier or divisor|area and volume applications"],
["math-07","Frequency Distribution Tables and Graphs","raw data|frequency|class intervals|tally marks|frequency tables|bar graphs|histograms|pie charts|reading graphs|misleading scales"],
["math-08","Exploring Geometrical Figures","polygons|interior angle sum|exterior angles|regular polygons|quadrilateral families|parallelograms|rectangles and squares|rhombus and kite|symmetry|tessellation"],
["math-09","Area of Plane Figures","rectangle and square|triangle|parallelogram|trapezium|rhombus and kite|circle measures|area of a circle|composite figures|unit conversion|area applications"],
["math-10","Direct and Inverse Proportions","direct proportion|constant of direct proportion|direct tables|unitary method|direct graphs|inverse proportion|constant product|work and time|speed and time|classifying proportion"],
["math-11","Algebraic Expressions","terms and factors|like and unlike terms|types of expressions|addition|subtraction|monomial multiplication|polynomial multiplication|identities|evaluation|verbal expressions"],
["math-12","Factorisation","factors and multiples|common factor|grouping|difference of squares|perfect square trinomials|splitting middle term|algebraic identities|verification|numerical factorisation|simplification"],
["math-13","Visualising 3-D in 2-D","faces edges vertices|nets|top front side views|isometric sketches|oblique sketches|maps and scale|Euler relation|cross-sections|counting cubes|spatial reasoning"],
["math-14","Surface Areas and Volume (Cube and Cuboid)","cube elements|cuboid elements|cuboid lateral area|cuboid total area|cube lateral area|cube total area|cuboid volume|cube volume|capacity conversion|applications"],
["math-15","Playing with Numbers","algebraic number form|reversing digits|place value|divisibility by 2 5 10|divisibility by 3 9|divisibility by 4 8|divisibility by 11|number puzzles|remainders|algebraic proof"]]},
"Physical Science":{icon:"⚛️",color:"#0369a1",chapters:[
["ps-01","Force","push and pull|effects of force|contact forces|non-contact forces|balanced forces|unbalanced forces|magnitude and direction|resultant force|force and pressure|daily applications"],
["ps-02","Friction","cause of friction|static friction|sliding friction|rolling friction|fluid friction|factors affecting friction|useful friction|harmful friction|reducing friction|increasing friction"],
["ps-03","Synthetic Fibres and Plastics","natural and synthetic fibres|polymers|rayon|nylon|polyester and acrylic|thermoplastics|thermosetting plastics|properties of plastics|environmental impact|responsible use"],
["ps-04","Metals and Non-metals","metal properties|non-metal properties|reaction with oxygen|reaction with water|reaction with acids|displacement reactions|reactivity series|uses of metals|uses of non-metals|corrosion prevention"],
["ps-05","Sound","production by vibration|human voice|need for a medium|compressions and rarefactions|amplitude and loudness|frequency and pitch|time period|audible range|human ear|noise pollution"],
["ps-06","Reflection of Light by Plane Surfaces","reflection|incident and reflected rays|first law of reflection|second law of reflection|regular reflection|diffuse reflection|plane mirror image|lateral inversion|multiple reflection|ray diagrams"],
["ps-07","Coal and Petroleum","fossil fuels|formation of coal|products of coal|formation of petroleum|petroleum refining|natural gas|petrochemicals|exhaustible resources|pollution impacts|conservation"],
["ps-08","Combustion, Fuels and Flame","combustion|ignition temperature|inflammable substances|fire triangle|types of combustion|zones of flame|complete combustion|incomplete combustion|calorific value|fire control"],
["ps-09","Electrical Conductivity of Liquids","conductors and insulators|liquid conduction|tester circuit|LED tester|conducting solutions|distilled and tap water|electrolysis|electroplating|uses of electroplating|electrical safety"],
["ps-10","Some Natural Phenomena","electric charge|charging by rubbing|electroscope|lightning|lightning safety|structure of Earth|earthquakes|focus and epicentre|seismic waves|earthquake preparedness"],
["ps-11","Stars and Solar System","celestial objects|stars|constellations|Pole Star|solar system|planets|rotation and revolution|phases of Moon|eclipses|asteroids comets meteors"],
["ps-12","Graphs of Motion","distance and displacement|speed|uniform motion|non-uniform motion|distance-time table|distance-time graph|meaning of slope|rest on a graph|comparing motion|journey graphs"]]},
"Biological Science":{icon:"🌱",color:"#15803d",chapters:[
["bio-01","What is Science?","scientific attitude|observation|questioning|hypothesis|experiment|measurement|evidence|variables|communication|revision of explanations"],
["bio-02","Cell - The Basic Unit of Life","cell theory|cell diversity|cell membrane|cytoplasm|nucleus|cell wall|vacuole|plastids|plant and animal cells|levels of organisation"],
["bio-03","The World of Microorganisms Part 1 & 2","microbial groups|viruses|microscopy|useful microbes|decomposition|nitrogen fixation|pathogens|transmission|food preservation|vaccination"],
["bio-04","Reproduction in Animals","purpose of reproduction|male system|female system|gametes|fertilisation|internal and external fertilisation|zygote and embryo|foetal development|oviparous and viviparous|metamorphosis"],
["bio-05","The Age of Adolescence","adolescence and puberty|hormones|secondary sexual characters|male changes|female changes|menstruation|emotional changes|nutrition|personal hygiene|healthy choices"],
["bio-06","Biodiversity - Conservation","biodiversity|species and habitat|flora and fauna|endemic species|threatened species|habitat loss|overexploitation and pollution|protected areas|in-situ and ex-situ conservation|citizen action"],
["bio-07","Different Ecosystems","ecosystem|biotic components|abiotic components|food chain|food web|energy flow|aquatic ecosystems|terrestrial ecosystems|adaptations|ecological balance"],
["bio-08","Production of Food from Plants","crop choice|soil preparation|seed selection and sowing|manure and fertiliser|irrigation|weed control|pest management|harvesting and threshing|storage|sustainable farming"],
["bio-09","Production of Food from Animals","animal husbandry|cattle management|dairy production|poultry|fisheries|bee keeping|feed and nutrition|selective breeding|disease prevention|animal welfare"],
["bio-10","Not for Breathing, Not for Drinking","air and water quality|air pollutants|sources of air pollution|health effects|water pollutants|water-borne disease|potable water|water purification|pollution control|community action"],
["bio-11","Why Do We Fall Ill?","health and disease|acute and chronic disease|infectious disease|non-infectious disease|disease agents|transmission routes|symptoms and diagnosis|prevention|immunity|public health"]]},
"Social Studies":{icon:"🌍",color:"#c2410c",chapters:[
["soc-01","Reading and Analysis of Maps","map and photograph|history of maps|scale|direction|symbols and colours|thematic maps|population maps|contours|atlas use|modern mapping"],
["soc-02","Energy from the Sun","solar radiation|unequal heating|temperature|land and water heating|air pressure|wind|global circulation|local winds|water cycle|weather and climate"],
["soc-03","Earth Movements and Seasons","rotation|day and night|revolution|axial tilt|seasons|solstices|equinoxes|hemispheres|length of day|leap year"],
["soc-04","The Polar Regions","location|extreme climate|tundra vegetation|animal adaptations|Arctic peoples|Antarctica|polar food webs|resources|climate change|conservation"],
["soc-05","Forests: Uses and Protection","forest types|forest products|ecological services|forest livelihoods|deforestation|consequences|commercial forestry|conservation|community participation|restoration"],
["soc-06","Minerals and Mining","meaning of mineral|types of minerals|distribution|mining methods|uses|livelihoods|environmental impacts|worker safety|displacement and rights|recycling"],
["soc-07","Money and Banking","barter limitations|functions of money|currency|bank services|savings|loans and credit|interest|collateral|formal and informal credit|digital payment safety"],
["soc-08","Impact of Technology on Livelihoods","technology and work|mechanisation|agricultural technology|industrial technology|communication technology|transport technology|new occupations|job displacement|skill development|inclusive technology"],
["soc-09","Public Health and the Government","public health|determinants of health|preventive care|curative care|government facilities|private healthcare|health inequality|epidemic control|public spending|citizen responsibility"],
["soc-10","Landlords and Tenants under the British and the Nizam","agrarian relations|land revenue|British settlements|zamindars and landlords|tenant cultivators|Nizam arrangements|debt and moneylenders|commercial crops|peasant resistance|long-term inequality"],
["soc-11a","National Movement - The Early Phase 1885-1919","colonial grievances|Indian National Congress|moderates|economic critique|partition of Bengal|Swadeshi|extremists|revolutionary activity|First World War|Home Rule"],
["soc-11b","National Movement - The Last Phase 1919-1947","Rowlatt Act and Jallianwala Bagh|Gandhian strategy|Non-Cooperation|Civil Disobedience|Salt March|social participation|constitutional negotiations|Quit India|INA|Independence and Partition"],
["soc-12","Freedom Movement in Hyderabad State","Hyderabad State|social structure|cultural organisations|Andhra Mahasabha|civil liberties|State Congress|peasant struggles|Telangana armed struggle|integration|legacy"],
["soc-13","The Indian Constitution","purpose of constitution|Constituent Assembly|Preamble|constitutional character|Fundamental Rights|Directive Principles|Fundamental Duties|federalism|parliamentary democracy|independent judiciary"],
["soc-14","Parliament and Central Government","Parliament|President|Lok Sabha|Rajya Sabha|Prime Minister and ministers|law-making|Question Hour|budget|majority and opposition|committees"],
["soc-15","Law and Justice - A Case Study","rule of law|need for law|police role|FIR|courts|fair trial|evidence|appeal|legal aid|access to justice"],
["soc-16","Abolition of Zamindari System","zamindari|tenant insecurity|need for reform|abolition laws|land ceilings|tenancy reform|land redistribution|implementation problems|Bhoodan|outcomes"],
["soc-17","Understanding Poverty","meaning of poverty|basic needs|poverty line|rural poverty|urban poverty|social exclusion|vulnerability|measurement limits|anti-poverty programmes|human development"],
["soc-18","Rights Approach to Development","development as a right|right to life|right to education|right to food|right to work|right to information|public services|accountability|participation|equity"],
["soc-19","Social and Religious Reform Movements","reform context|harmful customs|women's education|sati and widow remarriage|caste reform|Brahmo and Arya movements|Aligarh movement|Phule reform work|regional reformers|legacy"],
["soc-20","Understanding Secularism","secular state|freedom of religion|equality before law|principled distance|religious diversity|communalism|minority rights|constitutional safeguards|everyday secularism|challenges"],
["soc-21","Performing Arts and Artistes in Modern Times","performing arts|changing patronage|classical traditions|folk traditions|colonial modernity|nationalism|women performers|recording and broadcasting|cinema|preservation and innovation"],
["soc-22","Film and Print Media","print technology|newspapers|literacy and readership|film|media industries|advertising|representation|censorship and freedom|digital convergence|media literacy"],
["soc-23","Sports: Nationalism and Commerce","organised sport|colonial sport|cricket and nationalism|access to sport|international events|professionalisation|sponsorship|broadcast rights|fan culture|fair play"],
["soc-24","Disaster Management","hazard and disaster|natural hazards|human-made hazards|vulnerability|risk|mitigation|preparedness|response|recovery|community role"]]}}
const caps=s=>s.replace(/\b\w/g,c=>c.toUpperCase());
const rotate=(a,n)=>a.map((_,i)=>a[(i+n)%a.length]);
const build=(subject,[id,title,list])=>{const topics=list.split("|").map((name,i)=>({title:caps(name),text:`Understand ${name}, its key features and its use or importance in ${title}.`,example:`Textbook focus ${i+1}: connect ${name} with a definition, example, activity, map, diagram or problem from this chapter.`}));const cards=topics.flatMap((t,i)=>[[`Define ${t.title}.`,t.text],[`Key point: ${t.title}`,t.text],[`Which chapter includes ${t.title}?`,title],[`Recall cue ${i+1}: ${t.title}`,t.text],[`Explain ${t.title} in one sentence.`,t.text],[`Why is ${t.title} important?`,t.text],[`Complete the idea: ${t.title}…`,t.text],[t.text,t.title],[`Match the topic: ${t.title}`,t.text],[`Exam memory card: ${t.title}`,`${t.title} is an important part of ${title}. ${t.text}`]]);const quiz=topics.flatMap((t,i)=>Array.from({length:16},(_,v)=>{const other=rotate(topics,i+v+1).filter(x=>x.title!==t.title).slice(0,3),mode=v%4;if(mode===0)return[`Which topic belongs to ${title}?`,t.title,rotate([t.title,...other.map(x=>x.title)],v%4)];if(mode===1)return[`Choose the correct explanation of ${t.title}.`,t.text,rotate([t.text,...other.map(x=>x.text)],v%4)];if(mode===2)return[`“${t.text}” refers to:`,t.title,rotate([t.title,...other.map(x=>x.title)],(v+1)%4)];const answer=`${t.title} — ${t.text}`;return["Which topic-and-explanation pair is correct?",answer,rotate([answer,...other.map((x,j)=>`${x.title} — ${other[(j+1)%other.length].text}`)],v%4)]}));const writing=[...topics.map(t=>`Explain ${t.title} from ${title}. Include its meaning, importance and a suitable example.`),`Compare ${topics[0].title} and ${topics[1].title}.`,`Describe the connection between ${topics[2].title} and ${topics[3].title}.`,`Create a labelled flowchart or step sequence for ${title}.`,`Write five key points that summarise ${title}.`,`Apply two ideas from ${title} to a real-life situation.`].slice(0,15);return{id,title,intro:`Master 10 textbook-aligned topics through learning, recall, practice and writing.`,concepts:topics,cards,quiz,writing,write:writing[0],rubric:["Uses accurate terminology","Explains ideas logically","Includes an example, diagram, calculation or evidence","Ends with a clear conclusion"]}};
Object.entries(curriculum).forEach(([subject,data])=>data.chapters=data.chapters.map(ch=>build(subject,ch)));
window.CLASS8_CONTENT=curriculum;
})();
