import { firebaseConfig, SCRUTINY_ADMIN_EMAILS } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signOut, getIdTokenResult } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const chapters=['General Surgical Principles','Gastrointestinal Surgery','Hepatobiliary and Pancreatic Surgery','Colorectal Surgery','Breast Surgery','Endocrine Surgery','Vascular Surgery','Trauma and Emergency Surgery','Surgical Oncology','Urology','Pediatric Surgery','Thoracic Surgery','Transplant Surgery','Surgical Critical Care','Perioperative Care','Surgical Infections','Surgical Anatomy','Minimally Invasive and Robotic Surgery'];
const ready=new Set(['General Surgical Principles','Trauma and Emergency Surgery','Surgical Infections']);
const modules=[
 {id:'sepsis',title:'Surgical Sepsis & Source Control',chapter:'Surgical Infections',reference:'Surviving Sepsis Campaign 2021; WHO SSI guideline, 2018 update',summary:'Recognise organ dysfunction, resuscitate without delaying source control, and reassess repeatedly.',sections:[['Recognition','Suspect sepsis when infection is accompanied by acute organ dysfunction. Scores support—not replace—clinical judgment. Obtain cultures promptly when this does not materially delay antimicrobials.'],['Decision pathway','Stabilise airway/oxygenation → assess perfusion and lactate in context → begin appropriate antimicrobials → identify the anatomical source → choose the least physiologically costly effective source-control procedure → reassess response and de-escalate therapy.'],['High-yield trap','A normal blood pressure does not exclude occult hypoperfusion. Lactate is a risk marker, not a stand-alone diagnosis, and should be interpreted with examination, trend and alternative causes.']],pearl:'In uncontrolled surgical infection, antibiotics without source control are usually an incomplete treatment plan.'},
 {id:'shock',title:'Haemorrhagic Shock & Damage-Control Resuscitation',chapter:'Trauma and Emergency Surgery',reference:'ATLS principles; European major bleeding guideline, 2023',summary:'Control bleeding early, avoid dilutional resuscitation, correct the lethal diamond and choose definitive versus damage-control surgery.',sections:[['Immediate priorities','Activate haemorrhage control while securing airway and ventilation. Use balanced blood-component resuscitation according to the institutional massive-transfusion protocol; prevent hypothermia and monitor ionised calcium.'],['Decision pathway','Recognise shock → direct pressure/pelvic binder/operative or endovascular control → activate massive transfusion when indicated → give tranexamic acid early in eligible bleeding trauma patients → reassess physiology → definitive repair if stable, damage-control strategy if exhausted physiology.'],['High-yield trap','Permissive hypotension is not a universal rule. Avoid it in traumatic brain injury where cerebral perfusion must be preserved, and individualise it in pregnancy and chronic hypertension.']],pearl:'The endpoint is not a “normal” blood pressure; it is haemorrhage control with improving perfusion, temperature, coagulation and calcium.'},
 {id:'ssi',title:'SSI Prevention & Perioperative Antibiotics',chapter:'General Surgical Principles',reference:'CDC SSI guideline 2017; WHO SSI guideline, 2018 update',summary:'Match prophylaxis to procedure flora, deliver it before incision, redose when needed, and do not prolong it without an indication.',sections:[['Core concept','Prophylaxis prevents contamination from becoming infection; it does not sterilise tissue. Choose the narrowest regimen that covers expected organisms and local resistance patterns.'],['Decision pathway','Classify procedure → select drug/allergy alternative → administer so effective tissue concentration exists at incision → redose for prolonged surgery or major blood loss according to drug half-life → stop after the recommended prophylaxis window unless treating established infection.'],['High-yield trap','Continuing prophylactic antibiotics merely because a drain remains is not evidence-based. A drain is not, by itself, an indication for prolonged prophylaxis.']],pearl:'Correct timing and redosing are frequently more important than “stronger” or longer antibiotic therapy.'}
];
const questions=[
 {topic:'Surgical Infections',difficulty:'Hard',q:'A patient with perforated sigmoid diverticulitis remains vasopressor-dependent after initial resuscitation. CT shows free perforation and diffuse contamination. Which intervention most directly addresses the continuing driver of shock?',o:['Escalate to a broader antibiotic alone','Urgent operative source control','Repeat serum procalcitonin in 6 hours','Start parenteral nutrition'],a:1,why:'Diffuse contamination from a free perforation requires urgent source control alongside resuscitation and antimicrobials.',wrong:['Broader antibiotics cannot remove ongoing faecal contamination.','Correct.','A biomarker trend must not delay source control.','Nutrition is important later but does not control the septic source.'],ref:'Surviving Sepsis Campaign 2021'},
 {topic:'Surgical Infections',difficulty:'Medium',q:'Which statement about lactate in suspected surgical sepsis is most accurate?',o:['A normal lactate excludes septic shock','Lactate alone establishes the diagnosis of sepsis','Serial lactate can support perfusion reassessment but requires clinical context','Any elevation mandates laparotomy'],a:2,why:'Lactate is a prognostic/perfusion marker and trends can guide reassessment, but alternative causes and the clinical picture matter.',wrong:['Normal lactate does not exclude organ dysfunction.','Sepsis is a clinical syndrome, not a single-test diagnosis.','Correct.','Source control depends on anatomy and diagnosis, not lactate alone.'],ref:'Surviving Sepsis Campaign 2021'},
 {topic:'Surgical Infections',difficulty:'Easy',q:'In a patient with an infected obstructed collecting system and sepsis, the priority source-control principle is:',o:['Delay drainage until cultures identify the organism','Urgent decompression plus antimicrobials','Oral antibiotics and outpatient review','Definitive stone clearance before resuscitation'],a:1,why:'An infected obstructed system is a source-control emergency requiring prompt drainage with antibiotics and resuscitation.',wrong:['Cultures should not delay drainage.','Correct.','This is unsafe in sepsis with obstruction.','Initial decompression is usually prioritised over definitive stone treatment in an unstable patient.'],ref:'EAU Urolithiasis guideline principles'},
 {topic:'Surgical Infections',difficulty:'Medium',q:'After adequate source control for complicated intra-abdominal infection, the best antibiotic strategy is generally:',o:['Continue indefinitely until drains are removed','Use the shortest effective course guided by clinical response and current guidance','Always give at least 21 days','Stop immediately before the first dose'],a:1,why:'After adequate source control, unnecessarily prolonged therapy increases harm without improving outcomes; duration is tailored to response and diagnosis.',wrong:['Drains alone do not determine duration.','Correct.','A fixed 21-day minimum is unsupported.','Initial antimicrobial therapy is still required.'],ref:'WSES/SIS source-control principles'},
 {topic:'Trauma and Emergency Surgery',difficulty:'Hard',q:'A polytrauma patient has ongoing haemorrhage, temperature 34°C, worsening acidosis and diffuse coagulopathic bleeding. The most appropriate operative strategy is:',o:['Prolonged definitive reconstruction','Damage-control surgery with rapid haemorrhage/contamination control','Delay haemorrhage control for complete imaging','Large-volume cold crystalloid resuscitation'],a:1,why:'Physiological exhaustion with hypothermia, acidosis and coagulopathy favours abbreviated damage-control surgery and ICU correction before definitive reconstruction.',wrong:['Prolonged surgery worsens physiological exhaustion.','Correct.','Ongoing haemorrhage takes priority.','Cold crystalloid worsens dilution, hypothermia and coagulopathy.'],ref:'ATLS and damage-control surgery principles'},
 {topic:'Trauma and Emergency Surgery',difficulty:'Medium',q:'Permissive hypotension is least appropriate in which situation?',o:['Penetrating torso haemorrhage without brain injury','Suspected traumatic brain injury','Controlled external limb bleeding awaiting theatre','Short transfer with active abdominal bleeding'],a:1,why:'Hypotension threatens cerebral perfusion; traumatic brain injury requires avoidance of hypotension.',wrong:['This can be an eligible context before haemorrhage control.','Correct.','Management is individualised, but TBI is the clearest contraindicating context here.','This may be used cautiously if no contraindication exists.'],ref:'ATLS principles'},
 {topic:'Trauma and Emergency Surgery',difficulty:'Medium',q:'During massive transfusion, which electrolyte disturbance requires active surveillance because citrate can reduce the ionised fraction?',o:['Hypermagnesaemia','Hypocalcaemia','Hyperphosphataemia','Hypernatraemia'],a:1,why:'Citrate in blood products binds calcium; clinically important ionised hypocalcaemia can impair coagulation and cardiovascular function.',wrong:['Not the characteristic citrate-related disturbance.','Correct.','Not the principal citrate effect.','Not the principal citrate effect.'],ref:'European major bleeding guideline 2023'},
 {topic:'Trauma and Emergency Surgery',difficulty:'Easy',q:'The most important treatment for haemorrhagic shock is:',o:['Rapid haemorrhage control with appropriate resuscitation','Normalising haemoglobin before localisation','Routine bicarbonate for all acidosis','Vasopressors as the sole initial treatment'],a:0,why:'Definitive improvement requires stopping blood loss while supporting perfusion and correcting physiological derangement.',wrong:['Correct.','Waiting for a laboratory target delays control.','Bicarbonate does not correct ongoing tissue hypoperfusion.','Vasopressors do not replace blood or haemorrhage control.'],ref:'ATLS principles'},
 {topic:'General Surgical Principles',difficulty:'Medium',q:'For most indicated prophylactic antibiotics, the key timing principle is:',o:['Begin after skin closure','Ensure effective tissue concentration at incision','Give only when fever develops','Continue until every drain is removed'],a:1,why:'Prophylaxis should achieve effective tissue levels when contamination occurs—at incision—with agent-specific timing.',wrong:['This is too late for prophylaxis.','Correct.','That is treatment, not prophylaxis.','Drain presence alone does not justify prolonged prophylaxis.'],ref:'WHO SSI guideline 2018; CDC 2017'},
 {topic:'General Surgical Principles',difficulty:'Hard',q:'A long operation exceeds two drug half-lives and involves major blood loss. What is the best prophylaxis adjustment?',o:['No action because the first dose is always sufficient','Intraoperative redosing according to the agent and blood loss','Switch automatically to an antifungal','Continue the same antibiotic for seven days'],a:1,why:'Prolonged duration and major blood loss can reduce tissue concentration, making appropriate intraoperative redosing necessary.',wrong:['Concentrations may become subtherapeutic.','Correct.','Routine antifungal prophylaxis is not indicated.','Postoperative duration does not correct inadequate intraoperative exposure.'],ref:'CDC/WHO SSI prevention principles'},
 {topic:'General Surgical Principles',difficulty:'Easy',q:'Which statement about surgical drains and antibiotic prophylaxis is correct?',o:['Any drain mandates antibiotics until removal','A drain alone is not an indication to prolong prophylaxis','Drains eliminate SSI risk','Antibiotics should start only when the drain is removed'],a:1,why:'Prophylaxis should not be extended solely because a drain remains.',wrong:['This promotes harm and resistance without evidence.','Correct.','Drains can themselves be associated with complications.','This misses the prophylactic window.'],ref:'WHO SSI guideline 2018'},
 {topic:'General Surgical Principles',difficulty:'Medium',q:'Which approach best supports antimicrobial stewardship after surgery?',o:['Broaden therapy whenever CRP is elevated','Review cultures, anatomy, source control and clinical response, then de-escalate when appropriate','Use dual broad-spectrum therapy for every clean operation','Avoid documenting an intended duration'],a:1,why:'Stewardship requires repeated reassessment and narrowing/stopping based on microbiology, source control and clinical course.',wrong:['CRP alone is nonspecific.','Correct.','Clean procedures do not justify routine broad therapy.','Documented indication and duration improve safety.'],ref:'WHO/SSC antimicrobial stewardship principles'}
];
const cards=[['qSOFA purpose','A bedside risk prompt in suspected infection; it is not a stand-alone definition or screening replacement.'],['Source control','Remove/drain/debride the anatomical focus as soon as medically and logistically practical.'],['Lactate','Interpret trend and context; elevation is not specific for sepsis.'],['Septic vasopressor first line','Norepinephrine is the usual first-line vasopressor in adult septic shock.'],['Culture timing','Obtain before antimicrobials when this does not meaningfully delay treatment.'],['Antibiotic de-escalation','Narrow or stop based on cultures, source control and response.'],['Lethal diamond','Hypothermia, acidosis, coagulopathy and hypocalcaemia reinforce one another.'],['Damage-control surgery','Abbreviated control of bleeding/contamination followed by physiological restoration and later definitive repair.'],['Permissive hypotension exception','Avoid hypotension in traumatic brain injury; preserve cerebral perfusion.'],['Massive transfusion calcium','Citrate binds calcium; monitor ionised calcium.'],['TXA in trauma','Benefit is time-sensitive; use early in eligible major bleeding trauma patients according to protocol.'],['Pelvic binder','Place over the greater trochanters, not the iliac crests.'],['Prophylaxis goal','Adequate tissue concentration at the time of incision.'],['Redosing trigger','Prolonged surgery or major blood loss, adjusted to the antimicrobial half-life/protocol.'],['Drain trap','A drain alone is not an indication for prolonged prophylactic antibiotics.'],['Clean wound','Uninfected operative wound without entry into respiratory, alimentary, genital or uninfected urinary tract.'],['SSI prevention bundle','Combine evidence-based measures; no single intervention substitutes for sound technique.'],['Established infection','Requires therapeutic antibiotics and source control—not merely a longer “prophylaxis” course.']].map((x,i)=>({id:`f${i+1}`,front:x[0],back:x[1],topic:i<6?'Surgical Infections':i<12?'Trauma and Emergency Surgery':'General Surgical Principles'}));
const cases=[
 {title:'Perforation with septic shock',stem:'A 64-year-old has diffuse peritonitis, lactate 5.1 mmol/L and escalating norepinephrine. CT shows free colonic perforation.',choices:['Wait for lactate normalisation before surgery','Urgent source control while resuscitation continues','Escalate antibiotics and repeat CT tomorrow'],answer:1,explanation:'Resuscitation and source control proceed together; persistent anatomical contamination will continue to drive shock.'},
 {title:'Cold, coagulopathic trauma patient',stem:'After blunt trauma, the patient is bleeding, 34°C, acidotic and requires continuing transfusion.',choices:['Definitive multivisceral reconstruction now','Abbreviated damage-control operation','Stop transfusion until coagulation tests normalise'],answer:1,explanation:'Physiological exhaustion favours abbreviated haemorrhage/contamination control and ICU restoration before definitive repair.'},
 {title:'Drain after colorectal surgery',stem:'A stable patient has no evidence of infection on postoperative day 2. A pelvic drain remains.',choices:['Continue prophylaxis until drain removal','Stop prophylaxis according to the recommended window','Add antifungal prophylaxis'],answer:1,explanation:'A drain alone does not justify extending prophylactic antibiotics.'}
];
let user=null,profile={},founder=false,progress={uid:'',schemaVersion:1,completedModules:[],flashcards:{},bookmarks:[],attempts:[],mistakes:[],studyPlan:{dailyMinutes:60},updatedAt:null};
let quizIndex=0,quizScore=0,quizAnswers=[],cardIndex=0,difficultOnly=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function authorised(){return founder||profile.courseEntitlements?.neetss?.status==='active'}
function renderChapters(filter=''){const value=filter.toLowerCase();$('chapterGrid').innerHTML=chapters.filter(x=>x.toLowerCase().includes(value)).map((name,i)=>`<article class="chapter-card ${ready.has(name)?'ready':''}"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${name}</h3><p>${ready.has(name)?'Concept module, decision pathway, flashcards and reviewed starter questions are available.':'Roadmap defined. Content is scheduled for medically reviewed expansion.'}</p><small>${ready.has(name)?'PHASE 1 READY':'EXPANSION QUEUE'}</small></article>`).join('')||'<p>No matching chapter.</p>'}
function renderModules(){const tabs=$('moduleTabs');tabs.innerHTML=modules.map((m,i)=>`<button type="button" data-module="${i}" class="${i===0?'active':''}">${m.title}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>showModule(Number(b.dataset.module)));showModule(0)}
function showModule(index){document.querySelectorAll('#moduleTabs button').forEach((b,i)=>b.classList.toggle('active',i===index));const m=modules[index];$('moduleContent').innerHTML=`<span class="kicker">${m.chapter}</span><h3>${m.title}</h3><p>${m.summary}</p>${m.sections.map(([h,p])=>`<h4>${h}</h4>${h==='Decision pathway'?`<div class="algorithm">${p.split(' → ').map((s,i)=>`<div><b>STEP ${i+1}</b> · ${s}</div>`).join('')}</div>`:`<p>${p}</p>`}`).join('')}<p class="pearl"><strong>Clinical pearl:</strong> ${m.pearl}</p><p><small>Reference/version: ${m.reference}. Educational summary—apply current local protocols.</small></p><button class="primary" type="button" id="completeModule">${progress.completedModules.includes(m.id)?'COMPLETED ✓':'MARK MODULE COMPLETE'}</button>`;$('completeModule').onclick=()=>{if(!progress.completedModules.includes(m.id))progress.completedModules.push(m.id);saveProgress();showModule(index)}}
function setAccessUi(){const ok=authorised();$('workspace').hidden=!ok;$('learningModules').hidden=!ok;$('mcq-practice').hidden=!ok;$('clinical-cases').hidden=!ok;$('flashcards').hidden=!ok;$('mistake-book').hidden=!ok;$('analytics').hidden=!ok;$('logoutBtn').hidden=!user;if(!user){$('primaryAction').textContent='LOGIN / REGISTER';$('primaryAction').onclick=()=>location.href='index.html?mode=login#authCard';return}if(ok){$('accessTitle').textContent='Course access active';$('accessCopy').textContent='Your private attempts, mistakes, bookmarks and flashcard ratings are stored under your own Firebase UID.';$('loginLink').hidden=true;$('purchaseAccessBtn').hidden=true;$('primaryAction').textContent='OPEN COURSE DASHBOARD';$('primaryAction').onclick=()=>$('workspace').scrollIntoView({behavior:'smooth'});renderAll()}else{$('accessTitle').textContent='Secure enrolment required';$('accessCopy').textContent='Complete the Razorpay payment to unlock the course automatically. Founding Students pay ₹999 for the first 100 successful paid enrolments; the Early Bird Price is ₹1,999 afterward.';$('loginLink').hidden=true;$('purchaseAccessBtn').hidden=false;$('primaryAction').textContent='PAY & UNLOCK COURSE';$('primaryAction').onclick=()=>location.href='payment.html?course=neetss'}}
async function loadProgress(){try{const snap=await getDoc(doc(db,'neetssProgress',user.uid));if(snap.exists())progress={...progress,...snap.data()};progress.uid=user.uid}catch(e){console.warn('NEET-SS progress unavailable',e)}}
async function saveProgress(){if(!authorised()||!user)return;progress.uid=user.uid;progress.updatedAt=serverTimestamp();try{await setDoc(doc(db,'neetssProgress',user.uid),progress,{merge:false})}catch(e){console.error('NEET-SS progress save failed',e)}renderMetrics()}
function startQuiz(){quizIndex=0;quizScore=0;quizAnswers=[];showQuestion()}
function showQuestion(){if(quizIndex>=questions.length)return finishQuiz();const q=questions[quizIndex];$('quizBox').innerHTML=`<div class="quiz-head"><strong>Question ${quizIndex+1} of ${questions.length}</strong><span>${q.topic} · ${q.difficulty}</span></div><h3>${q.q}</h3><div class="quiz-options">${q.o.map((o,i)=>`<button type="button" data-option="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="questionFeedback"></div>`;$('quizBox').querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.option)))}
function answerQuestion(choice){const q=questions[quizIndex],correct=choice===q.a;quizScore+=correct?4:-1;quizAnswers.push({index:quizIndex,choice,correct,topic:q.topic});if(!correct&&!progress.mistakes.includes(quizIndex))progress.mistakes.push(quizIndex);if(correct)progress.mistakes=progress.mistakes.filter(i=>i!==quizIndex);const buttons=$('quizBox').querySelectorAll('[data-option]');buttons.forEach((b,i)=>{b.disabled=true;if(i===q.a)b.classList.add('correct');else if(i===choice)b.classList.add('wrong')});const next=()=>{quizIndex++;showQuestion()};if($('quizMode').value==='practice'){$('questionFeedback').innerHTML=`<div class="explanation"><strong>${correct?'Correct':'Incorrect'}.</strong> ${q.why}<ul>${q.o.map((o,i)=>`<li><b>${String.fromCharCode(65+i)}:</b> ${q.wrong[i]}</li>`).join('')}</ul><small>Reference: ${q.ref}</small></div><button class="primary" id="nextQuestion" type="button">${quizIndex===questions.length-1?'FINISH':'NEXT QUESTION'}</button>`;$('nextQuestion').onclick=next}else setTimeout(next,180)}
function finishQuiz(){const correct=quizAnswers.filter(x=>x.correct).length,attempt={date:new Date().toISOString(),attempted:questions.length,correct,score:quizScore,accuracy:Math.round(correct/questions.length*100),byTopic:{}};questions.forEach((q,i)=>{attempt.byTopic[q.topic]??={attempted:0,correct:0};attempt.byTopic[q.topic].attempted++;if(quizAnswers[i]?.correct)attempt.byTopic[q.topic].correct++});progress.attempts.unshift(attempt);progress.attempts=progress.attempts.slice(0,20);saveProgress();$('quizBox').innerHTML=`<h3>Practice complete</h3><p><strong>${quizScore}/${questions.length*4} marks</strong> · ${correct}/${questions.length} correct · ${attempt.accuracy}% accuracy</p><p>${progress.mistakes.length} question${progress.mistakes.length===1?'':'s'} now in your Mistake Book.</p><button class="primary" id="retryQuiz" type="button">RETRY SET</button>`;$('retryQuiz').onclick=startQuiz;renderAll()}
function renderCases(){$('caseGrid').innerHTML=cases.map((c,i)=>`<article class="case-card"><span class="kicker">CASE ${i+1}</span><h3>${c.title}</h3><p>${c.stem}</p>${c.choices.map((x,j)=>`<button class="secondary" type="button" data-case="${i}" data-choice="${j}">${x}</button>`).join('')}<div id="caseResult${i}"></div></article>`).join('');$('caseGrid').querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{const c=cases[Number(b.dataset.case)],correct=Number(b.dataset.choice)===c.answer;$(`caseResult${b.dataset.case}`).innerHTML=`<div class="case-result"><strong>${correct?'Best choice':'Reconsider'}:</strong> ${c.explanation}</div>`})}
function dueCards(){const difficult=cards.filter(c=>progress.flashcards[c.id]==='difficult');return difficultOnly?difficult:cards}
function renderCard(){const deck=dueCards();if(!deck.length){$('flashcardStage').innerHTML='<h3>No difficult cards marked yet.</h3><p>Show all cards and mark the concepts that need deliberate review.</p>';return}cardIndex%=deck.length;const c=deck[cardIndex];$('flashcardStage').innerHTML=`<span class="kicker">${c.topic} · ${cardIndex+1}/${deck.length}</span><h3>${c.front}</h3><p id="cardBack" hidden>${c.back}</p><div class="card-actions"><button type="button" id="revealCard">REVEAL ANSWER</button><button type="button" data-rate="known">I KNOW THIS</button><button type="button" data-rate="difficult">DIFFICULT</button><button type="button" id="nextCard">NEXT →</button></div>`;$('revealCard').onclick=()=>{$('cardBack').hidden=false};$('nextCard').onclick=()=>{cardIndex++;renderCard()};$('flashcardStage').querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{progress.flashcards[c.id]=b.dataset.rate;saveProgress();cardIndex++;renderCard()})}
function renderMistakes(){const list=progress.mistakes.map(i=>questions[i]).filter(Boolean);$('mistakeList').innerHTML=list.length?list.map((q,i)=>`<article><span class="kicker">${q.topic}</span><h3>${q.q}</h3><p><strong>Correct answer:</strong> ${q.o[q.a]}</p><p>${q.why}</p></article>`).join(''):'<p>No mistakes saved yet. Incorrect answers from the MCQ engine will appear here automatically.</p>'}
function renderMetrics(){const attempts=progress.attempts||[],total=attempts.reduce((s,a)=>s+a.attempted,0),correct=attempts.reduce((s,a)=>s+a.correct,0),accuracy=total?Math.round(correct/total*100):0,difficult=Object.values(progress.flashcards||{}).filter(x=>x==='difficult').length,mastery=Math.round(((progress.completedModules.length/modules.length)*40+(Math.min(total,questions.length)/questions.length)*40+(Object.keys(progress.flashcards).length/cards.length)*20));$('metricAttempts').textContent=total;$('metricAccuracy').textContent=`${accuracy}%`;$('metricMistakes').textContent=progress.mistakes.length;$('metricCards').textContent=difficult;$('progressRing').querySelector('strong').textContent=`${mastery}%`;$('analyticsPanel').innerHTML=`<article><span>Starter modules</span><strong>${progress.completedModules.length}/${modules.length}</strong><small>completed</small></article><article><span>Question accuracy</span><strong>${accuracy}%</strong><small>${total} attempts recorded</small></article><article><span>Revision load</span><strong>${progress.mistakes.length+difficult}</strong><small>mistakes + difficult cards</small></article>`}
function renderAll(){renderModules();renderCases();renderCard();renderMistakes();renderMetrics();$('welcomeName').textContent=`${profile.name||'Doctor'}, your Surgical Group command centre`}
$('courseSearch').oninput=e=>renderChapters(e.target.value);$('startQuiz').onclick=startQuiz;$('difficultOnly').onclick=()=>{difficultOnly=!difficultOnly;$('difficultOnly').textContent=difficultOnly?'SHOW ALL CARDS':'DIFFICULT CARDS ONLY';cardIndex=0;renderCard()};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'}));$('logoutBtn').onclick=async()=>{await signOut(auth);location.href='index.html?mode=login#authCard'};renderChapters();
onAuthStateChanged(auth,async current=>{user=current;if(!current){setAccessUi();return}try{const [student,token]=await Promise.all([getDoc(doc(db,'students',current.uid)),getIdTokenResult(current,true)]);profile=student.exists()?student.data():{};founder=token.claims.founder===true||SCRUTINY_ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((current.email||'').toLowerCase());if(authorised())await loadProgress();setAccessUi()}catch(e){console.error(e);$('accessMessage').textContent='Could not verify your student access. Please refresh or contact support.';$('accessMessage').className='message error'}});
