import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'data/manifest.json'), 'utf8'));
const bundle = {manifest};
for (const category of manifest.categories) {
  bundle[category.id] = {};
  for (const subject of category.subjects) {
    bundle[category.id][subject.id] = JSON.parse(fs.readFileSync(path.join(root, subject.file), 'utf8'));
  }
}
fs.writeFileSync(path.join(root, 'data/prebundled_data.js'), '/** Generated by node scripts/build-data.mjs. Do not edit directly. */\nwindow.SCRUTINY_DATA = '+JSON.stringify(bundle,null,2)+';\n');
console.log('Offline bundle rebuilt from manifest and subject JSON files.');
